<?php

define('USECASE_SIGNIN', 0);
define('USECASE_SIGNOUT', 1);
define('USECASE_UPDATE_PASSWORD', 2);
define('USECASE_UPDATE_PICTURE', 3);
define('USECASE_REQUEST_NEW_TRAINING', 4);
define('USECASE_ENROLL_TRAINING', 5);
define('USECASE_POST_NEW_TRAINING', 6);
define('USECASE_RESPOND_TO_ENROLLMENT', 7);
define('USECASE_RESPOND_TO_TRAING_REQUEST', 8);
define('USECASE_GENERATE_REPORT', 9);
define('USECASE_APPROVE_NEW_TRAINING', 10);
define('USECASE_ADD_USER_LEVEL', 11);
define('USECASE_ASSIGN_USECASE', 12);
define('USECASE_ADD_USER_TO_USERLEVEL', 13);

?>

